# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish npm

on:
  create

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: npm install -g yarn
      - run: yarn install
      - run: npm publish --access public
